version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "gtk"
        versions: '>= 0.10'
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
