changelog:
  categories:
    - title: '🚀 Features'
      label: 'enhancement'
    - title: '🐛 Bug Fixes'
      label: 'bug'
    - title: '📚 Documentation'
      label: 'documentation'
    - title: '🛠️ Refactoring'
      label: 'refactor'
    - title: '🚀 Performance'
      label: 'performance'
  exclude:
    labels:
      - 'skip-changelog'
